iou:
  meta_data_file: config/dnth_pokayoke.data
  image_root: features
  image_filetype: ".png"

yolo:
  weights_file: features/weights/yolov3-tiny_features_final.weights
  cfg_file: features/yolov3-tiny_features.cfg
  net_width: 416
  net_height: 416
  confidence_thr: 0.5
  nms_thr: 0.3

