iou:
  meta_data_file: /mnt/mydata/Documents/yolo_v4/darknet/cfg/dnth_pokayoke.data
  darknet_root: /mnt/mydata/Documents/yolo_v4/darknet
  image_filetype: ".png"

yolo:
  weights_file: /mnt/mydata/Documents/yolo_v4/darknet/output_weights/dnth_pokayoke_yolov3-tiny_201225/yolov3-tiny-dnth_pokayoke_final.weights
  cfg_file: /mnt/mydata/Documents/yolo_v4/darknet/cfg/yolov3-tiny-dnth_pokayoke.cfg
  net_width: 416
  net_height: 416
  confidence_thr: 0.5
  nms_thr: 0.3

